// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"30","screenWidth":"1018","screenHeight":"650","changeWindowWidthTo":"1018","changeWindowHeightTo":"650","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Oggy_1_3_1_MemoryLeakPatch","status":false,"description":"","parameters":{}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.2) 指定された番号のスイッチがONの間、\nプレイヤー操作によるキャラの移動を禁止します。","parameters":{"Default_Move_Flag":"10","Default_Menu_Flag":"true"}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"ON","ピクチャ番号の変数番号":"11","ポインタX座標の変数番号":"0","ポインタY座標の変数番号":"0","タッチ操作抑制":"ON","戦闘中常にコモン実行":"OFF"}},
{"name":"FixImageLoading","status":true,"description":"画像ロード時のチラつき防止プラグイン","parameters":{}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"350","Offset Y":"50","Width":"240","Background":"0"}},
{"name":"CustomizeConfigItem","status":true,"description":"オプション任意項目作成プラグイン","parameters":{"数値項目":"","文字項目":"","スイッチ項目":"[\"{\\\"Name\\\":\\\"ボイス\\\",\\\"DefaultValue\\\":\\\"true\\\",\\\"SwitchID\\\":\\\"20\\\",\\\"HiddenFlag\\\":\\\"false\\\",\\\"Script\\\":\\\"\\\",\\\"AddPosition\\\":\\\"\\\"}\"]","音量項目":""}}
];
